package com.team.medaibackend.service;

import com.team.medaibackend.entity.*;
import com.team.medaibackend.repository.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.*;

@Service
public class ConversationService {

    private final ConversationRepository conversationRepository;
    private final MessageRepository messageRepository;
    private final PatientRepository patientRepository;
    private final UserRepository userRepository;
    private final AuditService auditService;

    public ConversationService(
            ConversationRepository conversationRepository,
            MessageRepository messageRepository,
            PatientRepository patientRepository,
            UserRepository userRepository,
            AuditService auditService) {
        this.conversationRepository = conversationRepository;
        this.messageRepository = messageRepository;
        this.patientRepository = patientRepository;
        this.userRepository = userRepository;
        this.auditService = auditService;
    }

    /**
     * Get or create conversation between doctor and patient
     */
    @Transactional
    public Conversation getOrCreateConversation(Long doctorId, Long patientId) {
        // Check if conversation exists
        Optional<Conversation> existing = conversationRepository.findByDoctorIdAndPatientId(doctorId, patientId);
        if (existing.isPresent()) {
            return existing.get();
        }

        // Create new conversation
        User doctor = userRepository.findById(doctorId)
                .orElseThrow(() -> new RuntimeException("Doctor not found"));

        Patient patient = patientRepository.findById(patientId)
                .orElseThrow(() -> new RuntimeException("Patient not found"));

        Conversation conversation = new Conversation();
        conversation.setDoctor(doctor);
        conversation.setPatient(patient);
        conversation.setStatus("active");

        // UID will be generated by database trigger
        Conversation saved = conversationRepository.save(conversation);

        // Audit log
        auditService.log(
                "CONVERSATION_CREATED",
                "CONVERSATION",
                saved.getId().toString(),
                doctorId,
                doctor.getUsername()
        );

        return saved;
    }

    /**
     * Get conversation statistics
     */
    public Map<String, Object> getConversationStats(Long conversationId) {
        Map<String, Object> stats = new HashMap<>();

        List<Message> messages = messageRepository.findByConversationIdAndIsDeletedFalseOrderBySentAtAsc(conversationId);

        long totalMessages = messages.size();
        long unreadMessages = messages.stream().filter(m -> !m.getIsRead()).count();
        long textMessages = messages.stream().filter(m -> "text".equals(m.getMessageType())).count();
        long fileMessages = messages.stream().filter(m -> "file".equals(m.getMessageType())).count();
        long imageMessages = messages.stream().filter(m -> "image".equals(m.getMessageType())).count();

        stats.put("totalMessages", totalMessages);
        stats.put("unreadMessages", unreadMessages);
        stats.put("textMessages", textMessages);
        stats.put("fileMessages", fileMessages);
        stats.put("imageMessages", imageMessages);

        return stats;
    }

    /**
     * Archive conversation
     */
    @Transactional
    public Conversation archiveConversation(Long conversationId, User user) {
        Conversation conversation = conversationRepository.findById(conversationId)
                .orElseThrow(() -> new RuntimeException("Conversation not found"));

        conversation.setStatus("archived");
        Conversation saved = conversationRepository.save(conversation);

        auditService.log(
                "CONVERSATION_ARCHIVED",
                "CONVERSATION",
                saved.getId().toString(),
                user.getId(),
                user.getUsername()
        );

        return saved;
    }

    /**
     * Mute/unmute conversation
     */
    @Transactional
    public Conversation toggleMute(Long conversationId, User user) {
        Conversation conversation = conversationRepository.findById(conversationId)
                .orElseThrow(() -> new RuntimeException("Conversation not found"));

        conversation.setIsMuted(!conversation.getIsMuted());
        return conversationRepository.save(conversation);
    }

    /**
     * Get unread message count for doctor
     */
    public Long getUnreadCount(Long userId) {
        return messageRepository.countUnreadByDoctor(userId);
    }
}